config/routes.rb
Portfolio::Application.routes.draw do

  devise_for :users, controllers: {omniauth_callbacks: "omniauth_callbacks"}

  resources :projects do
    resources :comments
  end

  resources :posts do
    resources :comments
  end

match 'contact' => 'contact#new', :via => :get
match 'contact' => 'contact#create', :via => :post

  root to:"welcome#index"
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :commentable, polymorphic: true
end

app/models/message.rb
class Message
  include ActiveModel::Validations
  include ActiveModel::Conversion
  extend ActiveModel::Naming

  attr_accessor :name, :email, :subject, :body

  validates :name, :email, :subject,:body, :presence => true
  validates :email, :format => { :with => %r{.+@.+\..+} }, :allow_blank => true

  def initialize(attributes = {})
    attributes.each do |name,value|
      send("#{name}=", value)
    end
  end

  def persisted?
    false
  end
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :author, class_name: "User"
  has_many :comments, as: :commentable

  def publish!
    published = true
    save!
  end
end

app/models/project.rb
class Project < ActiveRecord::Base
  validates :name, length: { in: 4..255 }
  validates :technologies_used, presence: true

  has_many :comments, as: :commentable
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable
  has_many :posts, foreign_key: "author_id"

  def author?
    role == "author"
  end

  def editor?
    role == "editor"
  end

  def user?
    role == "user"
  end

  def self.from_omniauth(auth)
    where(auth.slice(:provider, :uid)).first_or_create do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.name = auth.info.nickname
      user.email = "#{user.name}-CHANGEME@twitter.example.com"
    end
  end

  def self.new_with_session(params, session)
    if session["devise.user_attributes"]
      new(session["devise.user_attributes"], without_protection: true ) do |user|
        user.attributes = params
        user.valid?
      end
    else
      super
    end
  end

  def password_required?
    super && provider.blank?
  end

  def update_with_password
    if encrypted_password.blank?
      update_attributes(params, *options)
    else
      super
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit

  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!
  before_action :load_commentable, only: [:create]

  def create
    @comment = @commentable.comments.new(comment_params)
    current_user.name.present? ? @comment.author = current_user.name : @comment.author = current_user.email

    if @comment.save
      redirect_to @commentable, success: "Comment submitted for moderation"
    else
      redirect_to @commentable, notice: "Comment could not be created"
    end
  end

  private

    def comment_params
      params.require(:comment).permit(:content, :commentable_id, :commentable_type, :author)
    end

    def load_commentable
      @resource, id = request.path.split('/')[1,2]
      @commentable = @resource.singularize.classify.constantize.find(id)
    end
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController

  def new
    @message = Message.new
  end

  def create
    @message = Message.new(params[:message])

    if @message.valid?
      NotificationsMailer.new_message(@message).deliver
      redirect_to(root_path, notice: "Message successfully sent")
    else
      flash.now.alert = "Please fill all fields"
      render :new
    end
  end
end

app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < ApplicationController
  def all
    user = User.from_omniauth(request.env["omniauth.auth"])
    if user.persisted?
      flash.notice = "#{user.name}, you are signed in!"
      sign_in_and_redirect user, notice:  "#{user.name}, you are signed in!"
    else
      session["devise.user_attributes"] = user.user_attributes
      redirect_to new_user_registration_url
    end
  end
  alias_method :twitter, :all
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user! , except: [ :index, :show ]
  before_action :set_post, only: [ :show, :edit, :update, :destroy ]

  def index
    @posts = Post.all
  end

  def show
    @commentable = @post
    @comments = @commentable.comments
    @comment = Comment.new
  end

  def new
    @post = Post.new
  end

  def edit
  end

  def create
    @post = Post.new(post_params)

    if policy(@post).create?
      if @post.save
        current_user.posts << @post
        redirect_to @post, notice: 'Post was successfully created.'
      else
        render action: 'new'
      end
    end
  end

  def update
    if @post.update(post_params)
      redirect_to @post, notice: 'Post was successfully updated.'
    else
      render action: 'edit'
    end
  end

  def destroy
    if @post.destroy
      redirect_to posts_url, notice: 'Post was destroyed'
    end
  end

  private

    def set_post
      @post = Post.find(params[:id])
    end

    def post_params
      params.require(:post).permit(:title, :body, (:published if current_user.role == "editor"))
    end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  def index
    @projects = Project.all
  end

  def new
    @project = Project.new
  end

  def create
    @project = Project.new(project_params)
    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: "Project has been created" }
        format.js
      else
        format.html{ render :new, error: "Project could not be saved" }
        format.js { render text: @project.errors.full_messages.join('. '), status: :unprocessable_entity }
      end
    end
  end

  def show
    @commentable = @project
    @comments = @commentable.comments
    @comment = Comment.new
  end

  def edit

  end

  def update
    respond_to do |format|
      if @project.update_attributes(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated'}
        format.js
      else
        format.html { render :edit, error: "Project could not be edited" }
        format.js { render text: @project.errors.full_messages.join('. '), status: :unprocessable_entity }
      end
    end
  end

  def destroy
    respond_to do |format|
      if @project.destroy
        format.html { redirect_to projects_path, notice: 'Project deleted' }
        format.js
      else
        format.html { redirect_to project_path(@project), error: "Project could not be deleted" }
        format.js { render text: @project.errors.full_messages.join('. '), status: :unprocessable_entity }
      end
    end
  end

  def set_project
    @project = Project.find(params[:id])
  end

  private

    def project_params
      params.require(:project).permit(:name, :technologies_used)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_class(level)
    case level
      when :notice then "success"
      when :success then "success"
      when :error then "alert"
      when :alert then "alert"
    end
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/omniauth_callbacks_helper.rb
module OmniauthCallbacksHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/contact/new.html.erb
<%= form_for @message, :url => contact_path do |form| %>
  <fieldset class="fields">
    <div class="field">
      <%= form.label :name %>
      <%= form.text_field :name %>
    </div>

    <div class="field">
      <%= form.label :email %>
      <%= form.text_field :email %>
    </div>
    <div class="field">
      <%= form.label :subject %>
      <%= form.text_field :subject %>
    </div>

    <div class="field">
      <%= form.label :body %>
      <%= form.text_area :body %>
    </div>
  </fieldset>

  <fieldset class="actions">
    <%= form.submit "Send" %>
  </fieldset>
<% end %>

app/views/layouts/_footer.html.erb
<div id="footer">

    <!-- First Column -->

        <div class="one-fourth">
            <h3>Useful Links</h3>
            <ul class="footer_links">
                <li><a href="http://github.com/Hobogrammer">Github</a></li>
                <li><a href="http://twitter.com/Hobogrammer">Twitter</a></li>
                <li><a href="http://www.linkedin.com/in/andrepsmith">LinkedIn</a></li>
            </ul>
        </div>

        <div style="clear:both"></div>

    </div> <!-- END footer -->

app/views/layouts/_header.html.erb
 <div class="header">

      <div id="site_title" class="circular"></div>

    <!-- Main Menu -->

      <ol id="menu">
           <li class="active_menu_item"><a href="index.html">Home</a>
            <li><a href="#">Portfolio</a>
             <li><a href="contact.html">Contact</a></li>
      </ol>
        <div class="user_header">
        <% if current_user %>
          <%= link_to "Sign Out", destroy_user_session_path, :method => :delete %>
        <% else %>
          <%= link_to "Sign Up",  new_user_registration_path %> or <%= link_to "Sign In", new_user_session_path %>
        <% end %>
        </div>
    </div><!-- END header -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7 ]> <html class="ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]>    <html class="ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]>    <html class="ie8" lang="en"> <![endif]-->
<!--[if IE 9 ]>    <html class="ie9" lang="en"> <![endif]-->
<!--[if (gt IE 9)|!(IE)]><!--> <html lang="en"> <!--<![endif]-->
  <head>
    <meta charset="utf-8" />

    <!-- Uncomment to make IE8 render like IE7 -->
    <!-- <meta http-equiv="X-UA-Compatible" content="IE=7" /> -->

    <!-- Set the viewport width to device width for mobile -->
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Andre 'Hobogrammer' Smith\'s Portfolio" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/custom.modernizr" %>
    <%= csrf_meta_tags %>
    <%= javascript_include_tag "application" %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <% flash.each do |key,value| %>
      <div class="alert-box round <%= flash_class(key) %>" >
          <%= value %>
      </div>
    <% end %>
    <div id="container">
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/posts/_form.html.erb
<%= simple_form_for @post do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.input :title %>
  <%= f.input :body %>
  <% if policy(@post).publish? %>
    <%= f.input :published %>
  <% end %>
  <%= f.button :submit %>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<h1>Recent posts</h1>

  <table>
    <thead>
      <tr>
        <th>Title</th>
        <th>Body</th>
        <th>Created at</th>
        <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <% @posts.each do |post| %>
        <tr>
          <td><%= post.title %></td>
          <td><%= post.body %></td>
          <td><%= l post.created_at, format: :long %></td>
          <td><%= link_to 'Show', post %></td>
          <% if policy(post).update? %>
            <td><%= link_to 'Edit', edit_post_path(post) %></td>
          <% end %>
          <% if policy(post).destroy? %>
            <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <% if policy(@posts).create? %>
    <%= link_to 'New Post', new_post_path, class: "button radius" %>
  <% end %>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>
<p>
    <b>By:</b>
    <%= @post.author.email %>
</p>

<p>
  <strong>Body:</strong>
  <%= @post.body %>
</p>

<p id="status">
  <b>Status:</b>
  <%= @post.published? ? "Published" : "Unpublished" %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>
<% if policy(@comment).create? %>
  <%= form_for [@commentable, @comment] do |f| %>
    <% if @comment.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this post from being saved:</h2>

        <ul>
        <% @comment.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

  <div class="field">
    <%= f.label :content %>
    <%= f.text_area :content %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>

  <% end %>
<% end %>

  <ol>
    <% @comments.each do |comment| %>
      <li><%= comment.author %>
        <p><%= comment.content %></p>
      </li>
    <% end %>
  </ol>

app/views/projects/_form.html.erb
<%= form_for(@project, remote: true) do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explaination">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>
      <ul>
        <% @project.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :technologies_used %>
    <%= f.text_field :technologies_used %>
  </div>
  <div class="actions">
    <%= f.submit  %>
  </div>
<% end %>

app/views/projects/_project.html.erb
<li id="project_<%= project.id %>">
  <h3><%= project.name %></h3>
  <p><%= project.technologies_used %></p>
  <div class="nav">
    <%= link_to 'Show', project_path(project) %> | <%= link_to 'Edit', edit_project_path(project), remote: true %> | <%= link_to 'Destroy', project, remote: true, method: :delete, data: { confirm: 'Are you sure?'} %>
  </div>
</li>

app/views/projects/create.js.erb
$('#new_project').remove();
$('#new_project_link').show();
$('#projects').append('<%= j render(@project) %>')

app/views/projects/destroy.js.erb
$('#project_<%= @project.id %>').remove();

app/views/projects/edit.html.erb
<h1>Edit Project</h1>

<%= render 'form' %>

<%= link_to "Cancel", :back %>

app/views/projects/edit.js.erb
$('#project_<%= @project.id %> .nav').hide().after('<%= j render "form" %>');

app/views/projects/index.html.erb
<h2>My Portfolio</h2>

<ul id="projects">
  <%= render (@projects) %>
</ul>

<br />
<%= link_to 'New Project', new_project_path, remote: true, id: "new_project_link" %>

app/views/projects/new.html.erb
<h2>New project</h2>

<%= render 'form' %>

<%= link_to 'Back', projects_path %>

app/views/projects/new.js.erb
$('#new_project_link').hide().after('<%= j render "form" %>')

app/views/projects/show.html.erb
<h2><%= @project.name %></h2>
<p>Technologies used:  <%= @project.technologies_used %></p>


<%= form_for [@commentable, @comment] do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :content %>
    <%= f.text_area :content %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>

<% end %>
<ol>
  <% @comments.each do |comment| %>
    <li><%= comment.author %>
      <p><%= comment.content %></p>
    </li>
  <% end %>
</ol>

app/views/projects/update.js.erb
$('#edit_project').remove();
$('#<%= dom_id @project %>').replaceWith('<%= j render @project %>');

app/views/welcome/index.html.erb
<div class="box_highlight" style="margin-top:40px"><h2 style="text-align:center">Web Developer. Problem Solver. Ruby on Rails Expert.</h2></div>

<div style="clear:both"></div>

<div class="heading_bg">
  <h2>Welcome to My Blog</h2>
  <p> Hello my name is Andre' Smith and I make awesome web applications. </p>
  <p> Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent justo ipsum, egestas ac cursus et, elementum et dolor. Etiam sem nisi, ullamcorper nec faucibus nec, elementum non odio. Curabitur bibendum ut nunc et pulvinar. Integer condimentum ullamcorper magna. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Quisque ut leo enim. Nullam non nisl augue. Nam non odio condimentum, ultricies mauris eu, accumsan quam. Mauris dapibus, massa vel pulvinar aliquet, arcu diam aliquet justo, sed condimentum orci enim sit amet odio. Maecenas in turpis mattis, euismod mauris ac, iaculis mi. Curabitur sagittis leo id purus placerat dictum. Curabitur a enim justo. Quisque velit lacus, pretium in libero eget, aliquet pretium lacus. Duis dapibus justo arcu, ac pellentesque augue bibendum nec.

Praesent luctus porta rutrum. Fusce tellus velit, pulvinar nec nulla in, scelerisque laoreet sapien. Vivamus aliquet ligula dui, ac sagittis metus adipiscing a. Aliquam non porta nibh. Proin suscipit, mi a consectetur tempus, ligula nisi vestibulum purus, id dapibus magna urna vitae augue. Nam hendrerit augue mi, quis sagittis mauris pulvinar ut. Suspendisse tristique ut mauris nec faucibus. Nam dignissim metus felis, vitae malesuada libero gravida non. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Maecenas fringilla laoreet pretium. Ut fringilla, dolor eget ultrices hendrerit, sem nunc varius elit, nec mattis lectus nisi et metus. In suscipit libero ligula, a rutrum purus scelerisque vitae. Ut venenatis feugiat blandit. Morbi at lacus ac mi egestas lacinia.</p>
</div>

  <br>

  <div style="clear:both"></div>